import { E } from '../sim/elements'
import type { Level } from './challenges'

// Level data. Each entry binds an archetype (see archetypes.ts) to params and
// flavour. Archetypes guarantee every level compiles, starts un-solved and is
// solvable with the intended elements — so authoring a level is pure data.
//
// The tier 1–3 curated seeds double as worked examples of each archetype; the
// rest were authored by the level-design workflow and validated headlessly
// against the real engine (`npm run validate`). `allowed: null` means the full
// palette — the puzzle is working out *which* element you need.

export const LEVELS: Level[] = [
  // ---- curated seeds --------------------------------------------------------
  {
    id: 'forest',
    name: 'Grow a Forest',
    objective: 'Cover the land in greenery — grow 200 plants.',
    hint: 'Drop seeds on damp soil by the pond; plants spread when watered.',
    tier: 1,
    archetype: 'growForest',
    params: { goal: 200 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: 'well',
    name: 'Fill the Well',
    objective: 'Fill the stone well to the brim with water.',
    hint: 'Pour water straight down the open shaft — it settles from the bottom.',
    tier: 1,
    archetype: 'fillVessel',
    params: { width: 14, ratio: 0.85 },
    allowed: [E.WATER],
  },
  {
    id: 'freeze',
    name: 'Freeze the Lake',
    objective: 'Turn the lake to solid ice.',
    hint: 'Snow and ice chill the water around them; bury the surface.',
    tier: 2,
    archetype: 'freezeLake',
    params: { ratio: 0.6 },
    allowed: [E.SNOW, E.ICE],
  },
  {
    id: 'firefighter',
    name: 'Save the Cabin',
    objective: 'Put out the fire and save most of the cabin.',
    hint: 'Water smothers fire instantly. Act fast — flames spread!',
    tier: 2,
    archetype: 'extinguish',
    params: { stamp: 'house', fuel: E.WOOD, keep: 0.55 },
    allowed: [E.WATER, E.SAND],
  },
  {
    id: 'glass',
    name: 'Forge Glass',
    objective: 'Fuse the sand bed into 140 panes of glass.',
    hint: 'Sand melts into glass when it gets blazing hot. Pour lava across it.',
    tier: 3,
    archetype: 'forgeGlass',
    params: { goal: 140 },
    allowed: [E.LAVA],
  },
  {
    id: 'obsidian',
    name: 'Quench the Lava',
    objective: 'Cool the lava lake into 120 blocks of obsidian.',
    hint: 'Water quenches lava on contact, hardening it into obsidian.',
    tier: 3,
    archetype: 'quenchLava',
    params: { goal: 120 },
    allowed: [E.WATER],
  },

  // ---- tier 1 · Sprout ------------------------------------------------------
  {
    id: 't1-first-sprouts',
    name: 'First Sprouts',
    objective: 'Grow a patch of green plants on the damp soil beside the pond.',
    hint: 'Drop seeds onto dirt near the water and let them sprout.',
    tier: 1,
    archetype: 'growForest',
    params: { goal: 130, pond: 12 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: 't1-fill-the-basin',
    name: 'Fill the Basin',
    objective: 'Pour water into the empty basin until it reaches the line.',
    hint: 'Just rain water down into the basin until it brims up.',
    tier: 1,
    archetype: 'collectWater',
    params: { ratio: 0.5 },
    allowed: [E.WATER],
  },
  {
    id: 't1-cold-snap',
    name: 'Cold Snap',
    objective: 'Freeze the little lake solid into ice.',
    hint: 'Pile snow and ice onto the water to chill it over.',
    tier: 1,
    archetype: 'freezeLake',
    params: { ratio: 0.5 },
    allowed: [E.SNOW, E.ICE],
  },
  {
    id: 't1-hanging-garden',
    name: 'Hanging Garden',
    objective: 'Cover the cliff overhang in trailing vines.',
    hint: 'Place vine along the ledge and it creeps downward on its own.',
    tier: 1,
    archetype: 'drapeVines',
    params: { goal: 110 },
    allowed: [E.VINE, E.WATER],
  },

  // ---- tier 2 · Apprentice --------------------------------------------------
  {
    id: 't2-spring-meadow',
    name: 'Spring Meadow',
    objective: 'Sow a thriving meadow across the soil.',
    hint: 'Seeds sprout on damp soil — keep them watered and they spread.',
    tier: 2,
    archetype: 'growForest',
    params: { goal: 160, pond: 14 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: 't2-cavern-geode',
    name: 'Cavern Geode',
    objective: 'Grow a glittering cluster of crystals beside the cavern pool.',
    hint: 'Seed crystals along the wet pool edge; water feeds their slow growth.',
    tier: 2,
    archetype: 'growCrystals',
    params: { goal: 90 },
    allowed: [E.CRYSTAL, E.WATER],
  },
  {
    id: 't2-sunken-cistern',
    name: 'Sunken Cistern',
    objective: 'Fill the empty stone basin up to the marked line.',
    hint: 'Pour water steadily until it reaches the fill line.',
    tier: 2,
    archetype: 'collectWater',
    params: { ratio: 0.55 },
    allowed: [E.WATER],
  },
  {
    id: 't2-furnace-sands',
    name: 'Furnace Sands',
    objective: 'Melt the sand bed into a sheet of clear glass.',
    hint: 'Pour lava over the sand; its heat fuses the grains into glass.',
    tier: 2,
    archetype: 'forgeGlass',
    params: { goal: 120 },
    allowed: [E.LAVA],
  },

  // ---- tier 3 · Tinkerer ----------------------------------------------------
  {
    id: 't3-acid-vault',
    name: 'Acid Vault',
    objective: 'Dissolve the sandstone vault wall to break in.',
    hint: 'Acid eats through sandstone — pour it along the top and let it sink.',
    tier: 3,
    archetype: 'dissolveBarrier',
    params: { barrier: E.SANDSTONE, width: 10, height: 22, leave: 0.1 },
    allowed: [E.ACID],
  },
  {
    id: 't3-powder-breach',
    name: 'Powder Breach',
    objective: 'Blow a clean breach through the rock wall.',
    hint: 'Pack gunpowder into the wall, then drop a spark to set the charge off.',
    tier: 3,
    archetype: 'blastWall',
    params: { width: 7, height: 28, clear: 0.45 },
    allowed: [E.GUNPOWDER, E.SPARK, E.FIRE],
  },
  {
    id: 't3-obsidian-tide',
    name: 'Obsidian Tide',
    objective: 'Quench the whole lava pool into a slab of obsidian.',
    hint: 'Water hitting lava sets it instantly into obsidian.',
    tier: 3,
    archetype: 'quenchLava',
    params: { goal: 110 },
    allowed: [E.WATER],
  },
  {
    id: 't3-curtain-of-vines',
    name: 'Curtain of Vines',
    objective: 'Drape the cliff overhang in a long curtain of vine.',
    hint: 'Anchor vine on the ledge — it creeps downward on its own; water feeds it.',
    tier: 3,
    archetype: 'drapeVines',
    params: { goal: 140 },
    allowed: [E.VINE, E.WATER],
  },

  // ---- tier 4 · Alchemist ---------------------------------------------------
  {
    id: 't4-sandstone-vault',
    name: 'The Sandstone Vault',
    objective: 'Dissolve the towering sandstone barrier almost entirely away.',
    hint: 'Acid eats through sandstone — pour enough to run down the whole height.',
    tier: 4,
    archetype: 'dissolveBarrier',
    params: { barrier: E.SANDSTONE, width: 12, height: 26, leave: 0.1 },
    allowed: [E.ACID],
  },
  {
    id: 't4-mirror-lake',
    name: 'Mirror Lake',
    objective: 'Freeze the entire lake solid into a sheet of ice.',
    hint: 'Bury the water in snow and seed it with ice to chill it over.',
    tier: 4,
    archetype: 'freezeLake',
    params: { ratio: 0.65 },
    allowed: null,
  },
  {
    id: 't4-emerald-cavern',
    name: 'Emerald Cavern',
    objective: 'Grow a glittering bed of crystals around the cavern pool.',
    hint: 'Seed crystal along the wet pool edge — water feeds the growth.',
    tier: 4,
    archetype: 'growCrystals',
    params: { goal: 110 },
    allowed: null,
  },
  {
    id: 't4-foundry-pour',
    name: 'Foundry Pour',
    objective: 'Fuse the wide sand bed into a sheet of glass.',
    hint: "Lava's heat melts sand into glass — flood the bed with it.",
    tier: 4,
    archetype: 'forgeGlass',
    params: { goal: 160 },
    allowed: [E.LAVA],
  },

  // ---- tier 5 · Elementalist ------------------------------------------------
  {
    id: 't5-wildfire-ward',
    name: 'Wildfire Ward',
    objective: 'Smother the blaze and save most of the timber.',
    hint: 'Only one liquid drowns fire on contact — and sand can starve it too.',
    tier: 5,
    archetype: 'extinguish',
    params: { stamp: 'house', fuel: E.WOOD, keep: 0.5 },
    allowed: null,
  },
  {
    id: 't5-boil-the-reservoir',
    name: 'Boil the Reservoir',
    objective: 'Flash the whole reservoir into a roiling cloud of steam.',
    hint: 'Water turns to steam only under fierce heat — drown the pan in lava.',
    tier: 5,
    archetype: 'boilOff',
    params: { goal: 120 },
    allowed: null,
  },
  {
    id: 't5-breach-the-keep',
    name: 'Breach the Keep',
    objective: 'Blow a gaping breach clean through the rock rampart.',
    hint: 'Pack the wall with gunpowder, then touch it off with a spark or flame.',
    tier: 5,
    archetype: 'blastWall',
    params: { width: 9, height: 34, clear: 0.5 },
    allowed: null,
  },
  {
    id: 't5-deep-cistern',
    name: 'The Deep Cistern',
    objective: 'Fill the deep stone cistern to the brim.',
    hint: 'Find the fluid that flows and settles, and pour it down the shaft.',
    tier: 5,
    archetype: 'fillVessel',
    params: { width: 18, ratio: 0.8 },
    allowed: null,
  },

  // ---- tier 6 · Worldsmith --------------------------------------------------
  {
    id: 't6-sealed-reliquary',
    name: 'The Sealed Reliquary',
    objective: 'Eat through the thick sandstone vault, leaving almost nothing.',
    hint: 'Acid devours sandstone — but not glass, gold, wall or obsidian. Pick the right solvent.',
    tier: 6,
    archetype: 'dissolveBarrier',
    params: { barrier: E.SANDSTONE, width: 14, height: 28, leave: 0.08 },
    allowed: null,
  },
  {
    id: 't6-tindergeist-manor',
    name: 'Tindergeist Manor',
    objective: 'Smother the blazing manor and rescue most of its timbers.',
    hint: 'Water drowns the flames; a little sand can starve stubborn embers.',
    tier: 6,
    archetype: 'extinguish',
    params: { stamp: 'house', fuel: E.WOOD, keep: 0.6 },
    allowed: null,
  },
  {
    id: 't6-collapsing-bastion',
    name: 'The Collapsing Bastion',
    objective: 'Punch a clean breach through the towering rock wall.',
    hint: 'Pack gunpowder against the stone, then touch it off with a single spark.',
    tier: 6,
    archetype: 'blastWall',
    params: { width: 9, height: 34, clear: 0.5 },
    allowed: null,
  },
  {
    id: 't6-cinderglass-foundry',
    name: 'Cinderglass Foundry',
    objective: 'Fuse the entire sand bed into a sheet of glass.',
    hint: 'Only fierce heat will do it; pour lava across the sand and let it fuse.',
    tier: 6,
    archetype: 'forgeGlass',
    params: { goal: 185 },
    allowed: null,
  },
]
