import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "blastWall" levels. Expand the game by appending entries here.
export const blastWall: Level[] = [
  {
    id: "x8-cracked-vault-door",
    name: "Cracked Vault Door",
    objective: "Pack the narrow breach with gunpowder and spark it to clear a third of the weak vault door.",
    hint: "Fill the slot with gunpowder, then drop a single spark to chain the explosion.",
    tier: 1,
    archetype: "blastWall",
    params: { width: 4, height: 20, clear: 0.3 },
    allowed: [E.GUNPOWDER, E.SPARK],
  },
  {
    id: "x8-powder-keg-gate",
    name: "Powder Keg Gate",
    objective: "Light a column of gunpowder to blow open nearly half of the timber gate.",
    hint: "Stack gunpowder against the gate and ignite it from below with fire.",
    tier: 2,
    archetype: "blastWall",
    params: { width: 5, height: 24, clear: 0.4 },
    allowed: [E.GUNPOWDER, E.SPARK, E.FIRE],
  },
  {
    id: "t3-powder-breach",
    name: "Powder Breach",
    objective: "Blow a clean breach through the rock wall.",
    hint: "Pack gunpowder into the wall, then drop a spark to set the charge off.",
    tier: 3,
    archetype: "blastWall",
    params: { width: 7, height: 28, clear: 0.45 },
    allowed: [E.GUNPOWDER, E.SPARK, E.FIRE],
  },
  {
    id: "x8-the-buried-tunnel",
    name: "The Buried Tunnel",
    objective: "Detonate enough gunpowder to carve out half of the collapsed tunnel wall.",
    hint: "Seed gunpowder through the whole wall before throwing the spark so the blast propagates.",
    tier: 3,
    archetype: "blastWall",
    params: { width: 6, height: 28, clear: 0.45 },
    allowed: [E.GUNPOWDER, E.SPARK, E.FIRE],
  },
  {
    id: "x8-siege-of-the-rampart",
    name: "Siege of the Rampart",
    objective: "Breach the thick rampart by clearing half of it with a chained powder blast.",
    hint: "A continuous gunpowder train carries the spark deep into the wall.",
    tier: 4,
    archetype: "blastWall",
    params: { width: 7, height: 30, clear: 0.5 },
    allowed: [E.GUNPOWDER, E.SPARK, E.FIRE, E.WALL],
  },
  {
    id: "t5-breach-the-keep",
    name: "Breach the Keep",
    objective: "Blow a gaping breach clean through the rock rampart.",
    hint: "Pack the wall with gunpowder, then touch it off with a spark or flame.",
    tier: 5,
    archetype: "blastWall",
    params: { width: 9, height: 34, clear: 0.5 },
    allowed: null,
  },
  {
    id: "x8-the-shattered-spire",
    name: "The Shattered Spire",
    objective: "Topple over half of the towering spire wall in a single detonation.",
    hint: "Only a packed explosive will clear this much, so build a gunpowder charge and ignite it.",
    tier: 5,
    archetype: "blastWall",
    params: { width: 9, height: 34, clear: 0.55 },
    allowed: null,
  },
  {
    id: "t6-collapsing-bastion",
    name: "The Collapsing Bastion",
    objective: "Punch a clean breach through the towering rock wall.",
    hint: "Pack gunpowder against the stone, then touch it off with a single spark.",
    tier: 6,
    archetype: "blastWall",
    params: { width: 9, height: 34, clear: 0.5 },
    allowed: null,
  },
  {
    id: "x8-the-great-bulwark",
    name: "The Great Bulwark",
    objective: "Bring down sixty percent of the massive bulwark with one overwhelming blast.",
    hint: "Deduce the explosive element, pack the full wall with it, and set it off.",
    tier: 6,
    archetype: "blastWall",
    params: { width: 10, height: 36, clear: 0.6 },
    allowed: null,
  },
]
