import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "boilOff" levels. Expand the game by appending entries here.
export const boilOff: Level[] = [
  {
    id: "x9-kettle-hollow",
    name: "Kettle Hollow",
    objective: "Boil away the shallow pool until 65 tiles of steam rise from the hollow.",
    hint: "Drip lava onto the water and let it hiss into steam.",
    tier: 1,
    archetype: "boilOff",
    params: { goal: 65 },
    allowed: [E.WATER, E.LAVA],
  },
  {
    id: "x9-the-simmer-trench",
    name: "The Simmer Trench",
    objective: "Heat the narrow trench until 85 tiles of water flash into steam.",
    hint: "Pour lava along the trench so every drop of water boils off.",
    tier: 2,
    archetype: "boilOff",
    params: { goal: 85 },
    allowed: [E.WATER, E.LAVA, E.WALL],
  },
  {
    id: "x9-scalded-grotto",
    name: "Scalded Grotto",
    objective: "Flood the grotto and cook it until 105 tiles of steam fill the cave.",
    hint: "Stone walls trap the heat, so let lava sink through and boil the water.",
    tier: 3,
    archetype: "boilOff",
    params: { goal: 105 },
    allowed: [E.WATER, E.LAVA, E.WALL, E.STONE],
  },
  {
    id: "x9-the-rendering-vats",
    name: "The Rendering Vats",
    objective: "Boil the brimming vats until 125 tiles of steam billow upward.",
    hint: "Channel lava into each metal vat to convert the water into steam.",
    tier: 4,
    archetype: "boilOff",
    params: { goal: 125 },
    allowed: [E.WATER, E.LAVA, E.METAL, E.WALL],
  },
  {
    id: "t5-boil-the-reservoir",
    name: "Boil the Reservoir",
    objective: "Flash the whole reservoir into a roiling cloud of steam.",
    hint: "Water turns to steam only under fierce heat — drown the pan in lava.",
    tier: 5,
    archetype: "boilOff",
    params: { goal: 120 },
    allowed: null,
  },
  {
    id: "x9-the-drowned-forge",
    name: "The Drowned Forge II",
    objective: "Reawaken the flooded forge by boiling 145 tiles of water into steam.",
    hint: "Only molten rock runs hot enough to flash the standing water to vapor.",
    tier: 5,
    archetype: "boilOff",
    params: { goal: 145 },
    allowed: null,
  },
  {
    id: "x9-leviathan-cauldron",
    name: "Leviathan Cauldron",
    objective: "Bring the vast cauldron to a roiling boil until 160 tiles of steam escape.",
    hint: "Deduce that a flood of lava is the only thing that will boil this much water away.",
    tier: 6,
    archetype: "boilOff",
    params: { goal: 160 },
    allowed: null,
  },
]
