import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "collectWater" levels. Expand the game by appending entries here.
export const collectWater: Level[] = [
  {
    id: "x12-dewdrop-cup",
    name: "Dewdrop Cup",
    objective: "Pour water until it settles into the little stone cup at the bottom.",
    hint: "Drop water straight down and let gravity pool it in the basin.",
    tier: 1,
    archetype: "collectWater",
    params: { ratio: 0.4 },
    allowed: [E.WATER],
  },
  {
    id: "t1-fill-the-basin",
    name: "Fill the Basin",
    objective: "Pour water into the empty basin until it reaches the line.",
    hint: "Just rain water down into the basin until it brims up.",
    tier: 1,
    archetype: "collectWater",
    params: { ratio: 0.5 },
    allowed: [E.WATER],
  },
  {
    id: "t2-sunken-cistern",
    name: "Sunken Cistern",
    objective: "Fill the empty stone basin up to the marked line.",
    hint: "Pour water steadily until it reaches the fill line.",
    tier: 2,
    archetype: "collectWater",
    params: { ratio: 0.55 },
    allowed: [E.WATER],
  },
  {
    id: "x12-trickling-trough",
    name: "Trickling Trough",
    objective: "Channel water along the trough until the catch-trough is half full.",
    hint: "Water spreads sideways, so feed one stream and let it flow into the dip.",
    tier: 2,
    archetype: "collectWater",
    params: { ratio: 0.45 },
    allowed: [E.WALL, E.WATER],
  },
  {
    id: "x12-thaw-the-snowpack",
    name: "Thaw the Snowpack",
    objective: "Melt the heaped snow so the runoff collects in the rocky catch below.",
    hint: "Snow becomes water when warmed, so melt the drifts and let the meltwater drain down.",
    tier: 3,
    archetype: "collectWater",
    params: { ratio: 0.5 },
    allowed: [E.WALL, E.WATER, E.SNOW, E.FIRE],
  },
  {
    id: "x12-glacier-melt",
    name: "Glacier Melt",
    objective: "Break the ice cap and gather the melt in the basin to over half its depth.",
    hint: "Ice yields water when it thaws, so apply heat to the frozen sheet and collect the runoff.",
    tier: 4,
    archetype: "collectWater",
    params: { ratio: 0.55 },
    allowed: [E.WALL, E.WATER, E.ICE, E.SNOW, E.FIRE, E.LAVA],
  },
  {
    id: "x12-monsoon-reservoir",
    name: "Monsoon Reservoir",
    objective: "Let the storm rain down until the reservoir is filled past the high-water mark.",
    hint: "Clouds shed rain that pools below, so seed the sky and let the downpour fill the catch.",
    tier: 5,
    archetype: "collectWater",
    params: { ratio: 0.62 },
    allowed: null,
  },
  {
    id: "x12-the-great-aqueduct",
    name: "The Great Aqueduct",
    objective: "Brim the vast cistern by routing every source of water you can muster.",
    hint: "Combine direct pours, rain from clouds, and melting ice to flood the deep catch to its limit.",
    tier: 6,
    archetype: "collectWater",
    params: { ratio: 0.7 },
    allowed: null,
  },
]
