import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "dissolveBarrier" levels. Expand the game by appending entries here.
export const dissolveBarrier: Level[] = [
  {
    id: "x7-rusted-grate",
    name: "The Rusted Grate",
    objective: "Dissolve the iron grate to drain the flooded shaft.",
    hint: "Pour acid over the barrier until it eats clean through.",
    tier: 1,
    archetype: "dissolveBarrier",
    params: { barrier: E.STONE, width: 6, height: 14, leave: 0.08 },
    allowed: [E.ACID],
  },
  {
    id: "x7-mossback-dam",
    name: "Mossback Dam",
    objective: "Eat away the old stone weir blocking the streambed.",
    hint: "Acid corrodes stone; let it trickle down the whole face.",
    tier: 2,
    archetype: "dissolveBarrier",
    params: { barrier: E.STONE, width: 8, height: 17, leave: 0.1 },
    allowed: [E.ACID, E.WATER],
  },
  {
    id: "t3-acid-vault",
    name: "Acid Vault",
    objective: "Dissolve the sandstone vault wall to break in.",
    hint: "Acid eats through sandstone — pour it along the top and let it sink.",
    tier: 3,
    archetype: "dissolveBarrier",
    params: { barrier: E.SANDSTONE, width: 10, height: 22, leave: 0.1 },
    allowed: [E.ACID],
  },
  {
    id: "x7-splintered-palisade",
    name: "Splintered Palisade",
    objective: "Rot through the wooden palisade penning the yard.",
    hint: "Drip acid along the timber to dissolve a breach.",
    tier: 3,
    archetype: "dissolveBarrier",
    params: { barrier: E.WOOD, width: 10, height: 20, leave: 0.12 },
    allowed: [E.ACID, E.OIL],
  },
  {
    id: "x7-the-bouldercap",
    name: "The Bouldercap",
    objective: "Bore through the rock plug sealing the cavern mouth.",
    hint: "Only acid will gnaw through this thick boulder.",
    tier: 4,
    archetype: "dissolveBarrier",
    params: { barrier: E.ROCK, width: 12, height: 24, leave: 0.14 },
    allowed: [E.ACID, E.WATER, E.STONE],
  },
  {
    id: "t4-sandstone-vault",
    name: "The Sandstone Vault",
    objective: "Dissolve the towering sandstone barrier almost entirely away.",
    hint: "Acid eats through sandstone — pour enough to run down the whole height.",
    tier: 4,
    archetype: "dissolveBarrier",
    params: { barrier: E.SANDSTONE, width: 12, height: 26, leave: 0.1 },
    allowed: [E.ACID],
  },
  {
    id: "x7-the-caustic-quarry",
    name: "The Caustic Quarry",
    objective: "Carve a passage through the sandstone quarry wall.",
    hint: "Find the one liquid that devours sandstone on contact.",
    tier: 5,
    archetype: "dissolveBarrier",
    params: { barrier: E.SANDSTONE, width: 14, height: 27, leave: 0.16 },
    allowed: null,
  },
  {
    id: "t6-sealed-reliquary",
    name: "The Sealed Reliquary",
    objective: "Eat through the thick sandstone vault, leaving almost nothing.",
    hint: "Acid devours sandstone — but not glass, gold, wall or obsidian. Pick the right solvent.",
    tier: 6,
    archetype: "dissolveBarrier",
    params: { barrier: E.SANDSTONE, width: 14, height: 28, leave: 0.08 },
    allowed: null,
  },
  {
    id: "x7-the-warden-monolith",
    name: "The Warden Monolith",
    objective: "Dissolve the towering rock monolith to release the depths.",
    hint: "Deduce the corrosive that alone can melt solid rock.",
    tier: 6,
    archetype: "dissolveBarrier",
    params: { barrier: E.ROCK, width: 16, height: 30, leave: 0.2 },
    allowed: null,
  },
]
