import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "drapeVines" levels. Expand the game by appending entries here.
export const drapeVines: Level[] = [
  {
    id: "t1-hanging-garden",
    name: "Hanging Garden",
    objective: "Cover the cliff overhang in trailing vines.",
    hint: "Place vine along the ledge and it creeps downward on its own.",
    tier: 1,
    archetype: "drapeVines",
    params: { goal: 110 },
    allowed: [E.VINE, E.WATER],
  },
  {
    id: "x11-mossfall-ledge",
    name: "Mossfall Ledge",
    objective: "Drape vines from the stone ledge until 80 tiles are clothed in green.",
    hint: "Plant vines on the overhang and let them creep downward over the edge.",
    tier: 1,
    archetype: "drapeVines",
    params: { goal: 80 },
    allowed: [E.VINE, E.WATER],
  },
  {
    id: "x11-creeper-archway",
    name: "Creeper Archway",
    objective: "Smother the old stone arch with 105 tiles of trailing vine.",
    hint: "Set vines along the top of the arch and water them so they cascade down both sides.",
    tier: 2,
    archetype: "drapeVines",
    params: { goal: 105 },
    allowed: [E.VINE, E.WATER, E.WALL],
  },
  {
    id: "t3-curtain-of-vines",
    name: "Curtain of Vines",
    objective: "Drape the cliff overhang in a long curtain of vine.",
    hint: "Anchor vine on the ledge — it creeps downward on its own; water feeds it.",
    tier: 3,
    archetype: "drapeVines",
    params: { goal: 140 },
    allowed: [E.VINE, E.WATER],
  },
  {
    id: "x11-the-veiled-trellis",
    name: "The Veiled Trellis",
    objective: "Cover the wooden trellis with at least 130 tiles of hanging vine.",
    hint: "Anchor vines to the upper beams and feed them water to drape the whole frame.",
    tier: 3,
    archetype: "drapeVines",
    params: { goal: 130 },
    allowed: [E.VINE, E.WATER, E.WOOD, E.WALL],
  },
  {
    id: "x11-ruins-of-greenmoor",
    name: "Ruins of Greenmoor",
    objective: "Reclaim the broken battlements with 155 tiles of creeping vine.",
    hint: "Seed vines atop the rubble and keep them watered so they pour over every gap.",
    tier: 4,
    archetype: "drapeVines",
    params: { goal: 155 },
    allowed: [E.VINE, E.WATER, E.STONE, E.ROCK, E.WALL],
  },
  {
    id: "x11-the-drowned-orangery",
    name: "The Drowned Orangery",
    objective: "Let the vine swallow the flooded glasshouse until 180 tiles are overgrown.",
    hint: "Deduce that watered vines, draped from the rafters, are the only way to clothe the ruin.",
    tier: 5,
    archetype: "drapeVines",
    params: { goal: 180 },
    allowed: null,
  },
  {
    id: "x11-cathedral-of-the-canopy",
    name: "Cathedral of the Canopy",
    objective: "Drown the towering nave in green until 200 tiles drip with living vine.",
    hint: "Anchor vines high and irrigate them so they cascade the full height of the hall.",
    tier: 6,
    archetype: "drapeVines",
    params: { goal: 200 },
    allowed: null,
  },
]
