import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "extinguish" levels. Expand the game by appending entries here.
export const extinguish: Level[] = [
  {
    id: "x6-ember-shed",
    name: "Smoldering Tool Shed",
    objective: "Douse the burning timber shed before its planks are eaten away.",
    hint: "Pour water straight down onto the flames to snuff them out.",
    tier: 1,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: [E.WATER, E.SAND],
  },
  {
    id: "x6-roadside-inn",
    name: "Roadside Inn Ablaze",
    objective: "Save the timbers of the burning wayside inn from the spreading fire.",
    hint: "Flood the flames with water and bank the embers under sand.",
    tier: 2,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: [E.WATER, E.SAND],
  },
  {
    id: "firefighter",
    name: "Save the Cabin",
    objective: "Put out the fire and save most of the cabin.",
    hint: "Water smothers fire instantly. Act fast — flames spread!",
    tier: 2,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: [E.WATER, E.SAND],
  },
  {
    id: "x6-millers-loft",
    name: "The Miller's Loft",
    objective: "Quench the blaze tearing through the old miller's wooden loft.",
    hint: "Smother the fire with water before it climbs the upper beams.",
    tier: 3,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: [E.WATER, E.SAND],
  },
  {
    id: "x6-thatched-hall",
    name: "Thatched Mead Hall",
    objective: "Put out the roaring fire engulfing the great thatched hall.",
    hint: "Drown the flames in water and pin the runaway embers with sand.",
    tier: 4,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: [E.WATER, E.SAND],
  },
  {
    id: "x6-watchtower-pyre",
    name: "Watchtower Pyre",
    objective: "Extinguish the towering blaze consuming the lonely wooden watchtower.",
    hint: "Find the liquid that smothers fire and rain it over the timbers.",
    tier: 5,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.45 },
    allowed: null,
  },
  {
    id: "t5-wildfire-ward",
    name: "Wildfire Ward",
    objective: "Smother the blaze and save most of the timber.",
    hint: "Only one liquid drowns fire on contact — and sand can starve it too.",
    tier: 5,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: null,
  },
  {
    id: "x6-cathedral-inferno",
    name: "Cathedral of Cinders",
    objective: "Save the vast burning timberwork of the great cathedral from total ruin.",
    hint: "Deduce the dousing liquid and bury stray embers under heaped sand.",
    tier: 6,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.4 },
    allowed: null,
  },
  {
    id: "t6-tindergeist-manor",
    name: "Tindergeist Manor",
    objective: "Smother the blazing manor and rescue most of its timbers.",
    hint: "Water drowns the flames; a little sand can starve stubborn embers.",
    tier: 6,
    archetype: "extinguish",
    params: { stamp: "house", fuel: E.WOOD, keep: 0.5 },
    allowed: null,
  },
]
