import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "fillVessel" levels. Expand the game by appending entries here.
export const fillVessel: Level[] = [
  {
    id: "well",
    name: "Fill the Well",
    objective: "Fill the stone well to the brim with water.",
    hint: "Pour water straight down the open shaft — it settles from the bottom.",
    tier: 1,
    archetype: "fillVessel",
    params: { width: 14, ratio: 0.85 },
    allowed: [E.WATER],
  },
  {
    id: "x2-the-clay-amphora",
    name: "The Clay Amphora",
    objective: "Pour water into the little amphora until it brims at the painted line.",
    hint: "Water falls and settles, filling the vessel from the bottom up.",
    tier: 1,
    archetype: "fillVessel",
    params: { width: 9, ratio: 0.72, fluid: E.WATER },
    allowed: [E.WATER],
  },
  {
    id: "x2-grandmas-kettle",
    name: "Grandma's Kettle",
    objective: "Top up the copper kettle with water for the morning brew.",
    hint: "Aim a steady water stream over the spout and let gravity do the rest.",
    tier: 2,
    archetype: "fillVessel",
    params: { width: 13, ratio: 0.76, fluid: E.WATER },
    allowed: [E.WATER],
  },
  {
    id: "x2-the-oil-cruet",
    name: "The Oil Cruet",
    objective: "Decant golden oil into the kitchen cruet up to the cork line.",
    hint: "Oil is a fluid too, so pour it in and watch it pool at the bottom.",
    tier: 3,
    archetype: "fillVessel",
    params: { width: 16, ratio: 0.8, fluid: E.OIL },
    allowed: [E.OIL],
  },
  {
    id: "x2-tavern-ale-vat",
    name: "Tavern Ale Vat",
    objective: "Charge the great oaken vat with water before the festival crowd arrives.",
    hint: "A wide vat needs a long, patient pour to flood every corner.",
    tier: 4,
    archetype: "fillVessel",
    params: { width: 20, ratio: 0.83, fluid: E.WATER },
    allowed: [E.WATER, E.WALL],
  },
  {
    id: "t5-deep-cistern",
    name: "The Deep Cistern",
    objective: "Fill the deep stone cistern to the brim.",
    hint: "Find the fluid that flows and settles, and pour it down the shaft.",
    tier: 5,
    archetype: "fillVessel",
    params: { width: 18, ratio: 0.8 },
    allowed: null,
  },
  {
    id: "x2-the-temple-font",
    name: "The Temple Font",
    objective: "Brim the sacred stone font for the dawn rite without spilling a drop.",
    hint: "Among everything on hand, only the pourable liquid will settle and fill the basin.",
    tier: 5,
    archetype: "fillVessel",
    params: { width: 24, ratio: 0.86, fluid: E.WATER },
    allowed: null,
  },
  {
    id: "x2-leviathans-trough",
    name: "Leviathan's Trough",
    objective: "Flood the colossal harbor trough to its highest mark for the docking beast.",
    hint: "Pick the flowing liquid and pour relentlessly to drown this enormous vessel.",
    tier: 6,
    archetype: "fillVessel",
    params: { width: 28, ratio: 0.9, fluid: E.WATER },
    allowed: null,
  },
]
