import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "forgeGlass" levels. Expand the game by appending entries here.
export const forgeGlass: Level[] = [
  {
    id: "x4-emberkiln-firstpane",
    name: "Emberkiln First Pane",
    objective: "Melt the sandbed into a single sheet of glass.",
    hint: "Pour lava over sand and it fuses into glass.",
    tier: 1,
    archetype: "forgeGlass",
    params: { goal: 90 },
    allowed: [E.SAND, E.LAVA],
  },
  {
    id: "x4-dunewright-workshop",
    name: "Dunewright Workshop",
    objective: "Fire the dune until enough panes of glass have formed.",
    hint: "Lava dripping across loose sand bakes it into glass.",
    tier: 2,
    archetype: "forgeGlass",
    params: { goal: 115 },
    allowed: [E.SAND, E.LAVA, E.STONE],
  },
  {
    id: "t2-furnace-sands",
    name: "Furnace Sands",
    objective: "Melt the sand bed into a sheet of clear glass.",
    hint: "Pour lava over the sand; its heat fuses the grains into glass.",
    tier: 2,
    archetype: "forgeGlass",
    params: { goal: 120 },
    allowed: [E.LAVA],
  },
  {
    id: "glass",
    name: "Forge Glass",
    objective: "Fuse the sand bed into 140 panes of glass.",
    hint: "Sand melts into glass when it gets blazing hot. Pour lava across it.",
    tier: 3,
    archetype: "forgeGlass",
    params: { goal: 140 },
    allowed: [E.LAVA],
  },
  {
    id: "x4-molten-glazier",
    name: "The Molten Glazier",
    objective: "Smelt the sand reserves into a wide glass casement.",
    hint: "Channel lava through the sand so the melt-front turns it to glass.",
    tier: 3,
    archetype: "forgeGlass",
    params: { goal: 135 },
    allowed: [E.SAND, E.LAVA, E.WALL],
  },
  {
    id: "x4-cinderdune-atelier",
    name: "Cinderdune Atelier",
    objective: "Run the lava kiln until the great pane is complete.",
    hint: "Sand kissed by lava vitrifies into glass.",
    tier: 4,
    archetype: "forgeGlass",
    params: { goal: 155 },
    allowed: [E.SAND, E.LAVA, E.STONE, E.WALL],
  },
  {
    id: "t4-foundry-pour",
    name: "Foundry Pour",
    objective: "Fuse the wide sand bed into a sheet of glass.",
    hint: "Lava's heat melts sand into glass — flood the bed with it.",
    tier: 4,
    archetype: "forgeGlass",
    params: { goal: 160 },
    allowed: [E.LAVA],
  },
  {
    id: "x4-the-vitrifier",
    name: "The Vitrifier's Vigil",
    objective: "Forge a vast field of glass from the buried sands.",
    hint: "Find the molten element that fuses sand into glass.",
    tier: 5,
    archetype: "forgeGlass",
    params: { goal: 175 },
    allowed: null,
  },
  {
    id: "x4-cataclysm-foundry",
    name: "Cataclysm Foundry",
    objective: "Vitrify the entire desert into one colossal sheet of glass.",
    hint: "Only an unrelenting flood of the hottest molten element can smelt this much sand to glass.",
    tier: 6,
    archetype: "forgeGlass",
    params: { goal: 200 },
    allowed: null,
  },
  {
    id: "t6-cinderglass-foundry",
    name: "Cinderglass Foundry",
    objective: "Fuse the entire sand bed into a sheet of glass.",
    hint: "Only fierce heat will do it; pour lava across the sand and let it fuse.",
    tier: 6,
    archetype: "forgeGlass",
    params: { goal: 185 },
    allowed: null,
  },
]
