import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "freezeLake" levels. Expand the game by appending entries here.
export const freezeLake: Level[] = [
  {
    id: "t1-cold-snap",
    name: "Cold Snap",
    objective: "Freeze the little lake solid into ice.",
    hint: "Pile snow and ice onto the water to chill it over.",
    tier: 1,
    archetype: "freezeLake",
    params: { ratio: 0.5 },
    allowed: [E.SNOW, E.ICE],
  },
  {
    id: "x3-frostfall-puddle",
    name: "Frostfall Puddle",
    objective: "Freeze a small woodland puddle solid before the thaw.",
    hint: "Drop SNOW onto the WATER so it chills into ICE.",
    tier: 1,
    archetype: "freezeLake",
    params: { ratio: 0.4 },
    allowed: [E.SNOW, E.ICE, E.WATER],
  },
  {
    id: "freeze",
    name: "Freeze the Lake",
    objective: "Turn the lake to solid ice.",
    hint: "Snow and ice chill the water around them; bury the surface.",
    tier: 2,
    archetype: "freezeLake",
    params: { ratio: 0.6 },
    allowed: [E.SNOW, E.ICE],
  },
  {
    id: "x3-quiet-millpond",
    name: "Quiet Millpond",
    objective: "Ice over the calm millpond behind the old wheel.",
    hint: "Blanket the surface with SNOW until it sets into ICE.",
    tier: 2,
    archetype: "freezeLake",
    params: { ratio: 0.5 },
    allowed: [E.SNOW, E.ICE, E.WATER],
  },
  {
    id: "x3-glacier-tarn",
    name: "Glacier Tarn",
    objective: "Seal the mountain tarn under a sheet of ice.",
    hint: "Pile SNOW across the WATER to crystallize it into ICE.",
    tier: 3,
    archetype: "freezeLake",
    params: { ratio: 0.55 },
    allowed: [E.SNOW, E.ICE, E.WATER, E.WALL],
  },
  {
    id: "t4-mirror-lake",
    name: "Mirror Lake",
    objective: "Freeze the entire lake solid into a sheet of ice.",
    hint: "Bury the water in snow and seed it with ice to chill it over.",
    tier: 4,
    archetype: "freezeLake",
    params: { ratio: 0.65 },
    allowed: null,
  },
  {
    id: "x3-the-skater-s-bay",
    name: "The Skater's Bay",
    objective: "Freeze the broad bay thick enough for skating.",
    hint: "Smother the WATER with SNOW so the whole bay turns to ICE.",
    tier: 4,
    archetype: "freezeLake",
    params: { ratio: 0.62 },
    allowed: [E.SNOW, E.ICE, E.WATER, E.WALL, E.STONE],
  },
  {
    id: "x3-the-frozen-fjord",
    name: "The Frozen Fjord",
    objective: "Lock the deep fjord beneath a vast crust of ice.",
    hint: "Bury the water in falling SNOW until it hardens into ICE.",
    tier: 5,
    archetype: "freezeLake",
    params: { ratio: 0.7 },
    allowed: null,
  },
  {
    id: "x3-the-endless-icecap",
    name: "The Endless Icecap",
    objective: "Freeze the entire frigid sea into one continuous icecap.",
    hint: "Cool every drop of water with SNOW so it all converts to ICE.",
    tier: 6,
    archetype: "freezeLake",
    params: { ratio: 0.75 },
    allowed: null,
  },
]
