import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "growForest" levels. Expand the game by appending entries here.
export const growForest: Level[] = [
  {
    id: "x1-acorn-cradle",
    name: "Acorn Cradle",
    objective: "Coax a tiny stand of saplings to life around a small forest pool.",
    hint: "Drop seeds onto wet dirt beside the pond and let the water feed them.",
    tier: 1,
    archetype: "growForest",
    params: { goal: 130, pond: 8 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "t1-first-sprouts",
    name: "First Sprouts",
    objective: "Grow a patch of green plants on the damp soil beside the pond.",
    hint: "Drop seeds onto dirt near the water and let them sprout.",
    tier: 1,
    archetype: "growForest",
    params: { goal: 130, pond: 12 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "forest",
    name: "Grow a Forest",
    objective: "Cover the land in greenery — grow 200 plants.",
    hint: "Drop seeds on damp soil by the pond; plants spread when watered.",
    tier: 1,
    archetype: "growForest",
    params: { goal: 200 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "t2-spring-meadow",
    name: "Spring Meadow",
    objective: "Sow a thriving meadow across the soil.",
    hint: "Seeds sprout on damp soil — keep them watered and they spread.",
    tier: 2,
    archetype: "growForest",
    params: { goal: 160, pond: 14 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "x1-willow-shallows",
    name: "Willow Shallows",
    objective: "Grow a leafy thicket along the muddy shallows of a quiet pond.",
    hint: "Seeds sprout fastest where seeds, water, and damp dirt all meet.",
    tier: 2,
    archetype: "growForest",
    params: { goal: 155, pond: 11 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "x1-fernhollow-rise",
    name: "Fernhollow Rise",
    objective: "Raise a broad belt of greenery across the hollow's wet floor.",
    hint: "Keep the pond fed so the dirt stays soaked and every seed takes root.",
    tier: 3,
    archetype: "growForest",
    params: { goal: 185, pond: 14 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "x1-mistwood-basin",
    name: "Mistwood Basin",
    objective: "Blanket the basin in dense foliage drawn up from its central pool.",
    hint: "Layer dirt over the pond first, then sow seeds onto the soaked soil.",
    tier: 4,
    archetype: "growForest",
    params: { goal: 210, pond: 17 },
    allowed: [E.SEED, E.WATER, E.DIRT],
  },
  {
    id: "x1-emberwild-canopy",
    name: "Emberwild Canopy",
    objective: "Reclaim the scorched clearing with a sprawling new canopy.",
    hint: "Only watered seeds on soil will sprout, so pair every seed with the pond.",
    tier: 5,
    archetype: "growForest",
    params: { goal: 235, pond: 20 },
    allowed: null,
  },
  {
    id: "x1-primeval-greenwald",
    name: "Primeval Greenwald",
    objective: "Smother the whole valley in an ancient, unbroken sea of green.",
    hint: "Flood dirt into a wide wet bed and saturate it with seeds to chain-grow the forest.",
    tier: 6,
    archetype: "growForest",
    params: { goal: 260, pond: 22 },
    allowed: null,
  },
]
