import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "growCrystals" levels. Expand the game by appending entries here.
export const growCrystals: Level[] = [
  {
    id: "x10-frost-seed-vial",
    name: "Frost Seed Vial",
    objective: "Grow at least 55 units of crystal inside the sealed glass vial.",
    hint: "Place a few crystal seeds and let water feed their slow spread.",
    tier: 1,
    archetype: "growCrystals",
    params: { goal: 55 },
    allowed: [E.CRYSTAL, E.WATER],
  },
  {
    id: "t2-cavern-geode",
    name: "Cavern Geode",
    objective: "Grow a glittering cluster of crystals beside the cavern pool.",
    hint: "Seed crystals along the wet pool edge; water feeds their slow growth.",
    tier: 2,
    archetype: "growCrystals",
    params: { goal: 90 },
    allowed: [E.CRYSTAL, E.WATER],
  },
  {
    id: "x10-prism-nook",
    name: "The Prism Nook",
    objective: "Encrust the little nook with 70 units of crystal.",
    hint: "Seed crystal beside standing water so the lattice keeps climbing.",
    tier: 2,
    archetype: "growCrystals",
    params: { goal: 70 },
    allowed: [E.CRYSTAL, E.WATER, E.WALL],
  },
  {
    id: "x10-shimmer-hollow",
    name: "Shimmer Hollow",
    objective: "Fill the hollow with 85 units of grown crystal.",
    hint: "Keep water pooled against the crystal so growth never starves.",
    tier: 3,
    archetype: "growCrystals",
    params: { goal: 85 },
    allowed: [E.CRYSTAL, E.WATER, E.WALL, E.STONE],
  },
  {
    id: "t4-emerald-cavern",
    name: "Emerald Cavern",
    objective: "Grow a glittering bed of crystals around the cavern pool.",
    hint: "Seed crystal along the wet pool edge — water feeds the growth.",
    tier: 4,
    archetype: "growCrystals",
    params: { goal: 110 },
    allowed: null,
  },
  {
    id: "x10-glacier-reliquary",
    name: "Glacier Reliquary",
    objective: "Cultivate 100 units of crystal across the frozen reliquary.",
    hint: "Melt the ice into feed-water and let several crystal seeds bloom at once.",
    tier: 4,
    archetype: "growCrystals",
    params: { goal: 100 },
    allowed: [E.CRYSTAL, E.WATER, E.ICE, E.WALL, E.STONE],
  },
  {
    id: "x10-deep-vein-grotto",
    name: "Deep Vein Grotto",
    objective: "Grow 120 units of crystal through the unmarked grotto.",
    hint: "Deduce that crystal seeds fed by water are what spread the glittering vein.",
    tier: 5,
    archetype: "growCrystals",
    params: { goal: 120 },
    allowed: null,
  },
  {
    id: "x10-the-everbloom-cathedral",
    name: "The Everbloom Cathedral",
    objective: "Overgrow the vast cathedral with 140 units of living crystal.",
    hint: "Crystal is the only element that multiplies here, and water is what keeps it blooming.",
    tier: 6,
    archetype: "growCrystals",
    params: { goal: 140 },
    allowed: null,
  },
]
