import { E } from '../../sim/elements'
import type { Level } from '../challenges'

// "quenchLava" levels. Expand the game by appending entries here.
export const quenchLava: Level[] = [
  {
    id: "x5-ashfall-hollow",
    name: "Ashfall Hollow",
    objective: "Pour water onto the small lava pool until 90 tiles harden into obsidian.",
    hint: "Water striking lava freezes it into obsidian.",
    tier: 1,
    archetype: "quenchLava",
    params: { goal: 90 },
    allowed: [E.WATER, E.LAVA],
  },
  {
    id: "x5-smolderpit-trench",
    name: "Smolderpit Trench",
    objective: "Quench the trench of lava, converting 110 tiles to obsidian.",
    hint: "Let cascading water flood across the lava to skin it in obsidian.",
    tier: 2,
    archetype: "quenchLava",
    params: { goal: 110 },
    allowed: [E.WATER, E.LAVA, E.WALL],
  },
  {
    id: "t3-obsidian-tide",
    name: "Obsidian Tide",
    objective: "Quench the whole lava pool into a slab of obsidian.",
    hint: "Water hitting lava sets it instantly into obsidian.",
    tier: 3,
    archetype: "quenchLava",
    params: { goal: 110 },
    allowed: [E.WATER],
  },
  {
    id: "obsidian",
    name: "Quench the Lava",
    objective: "Cool the lava lake into 120 blocks of obsidian.",
    hint: "Water quenches lava on contact, hardening it into obsidian.",
    tier: 3,
    archetype: "quenchLava",
    params: { goal: 120 },
    allowed: [E.WATER],
  },
  {
    id: "x5-the-glowing-vein",
    name: "The Glowing Vein",
    objective: "Cool the molten vein threading the rock until 125 obsidian tiles form.",
    hint: "Channel water along the vein so every lava cell meets it and sets.",
    tier: 3,
    archetype: "quenchLava",
    params: { goal: 125 },
    allowed: [E.WATER, E.LAVA, E.WALL, E.STONE],
  },
  {
    id: "x5-caldera-shroud",
    name: "Caldera Shroud",
    objective: "Cap the bubbling caldera, hardening 145 tiles of lava into obsidian.",
    hint: "Drench the open lava surface with water; the cooled crust becomes obsidian.",
    tier: 4,
    archetype: "quenchLava",
    params: { goal: 145 },
    allowed: [E.WATER, E.LAVA, E.WALL, E.STONE, E.ROCK],
  },
  {
    id: "x5-the-magma-cistern",
    name: "The Magma Cistern",
    objective: "Drown the brimming magma cistern until 160 obsidian tiles are set.",
    hint: "Find the element that turns lava to obsidian and flood the cistern with it.",
    tier: 5,
    archetype: "quenchLava",
    params: { goal: 160 },
    allowed: null,
  },
  {
    id: "x5-the-drowned-forge",
    name: "The Drowned Forge",
    objective: "Extinguish the great molten forge, converting 180 tiles into obsidian.",
    hint: "Deduce which liquid quenches lava and pour enough of it to skin the whole pool in obsidian.",
    tier: 6,
    archetype: "quenchLava",
    params: { goal: 180 },
    allowed: null,
  },
]
